<a href="https://colab.research.google.com/github/Kevin101504/Machine-Learning-Lab/blob/main/Ml_Experiment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np
from scipy.optimize import linear_sum_assignment

In [ ]:
#Load inbuilt Iris dataset
iris=load_iris()
X=iris.data
y=iris.target #actual labels

In [ ]:
#Apply KMeans
kmeans = KMeans(n_clusters=3,random_state=42,n_init="auto")
y_kmeans = kmeans.fit_predict(X)

In [ ]:
#Create DataFrame
df=pd.DataFrame(X,columns=iris.feature_names)
df['Actual']=y
df['Cluster']=y_kmeans
print("Cluster Centers:\n",pd.DataFrame(kmeans.cluster_centers_,columns=iris.feature_names))
print("\nSample clustered \n",df.head())


Cluster Centers:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           6.853846          3.076923           5.715385          2.053846
1           5.006000          3.428000           1.462000          0.246000
2           5.883607          2.740984           4.388525          1.434426

Sample clustered 
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Actual  Cluster  
0       0        1  
1       0        1  
2       0        1  
3       0        1  
4       0        1  


In [ ]:
#Evaluate clustering
cm = confusion_matrix(y,y_kmeans)
print("\nConfusion Matrix:\n",cm)


Confusion Matrix:
 [[ 0 50  0]
 [ 3  0 47]
 [36  0 14]]


In [ ]:
#Align cluster labels to true labels using Hungarian algorithm for accuracy
row_ind,col_ind = linear_sum_assignment(cm.max()-cm)
aligned_labels = np.zeros_like(y_kmeans)
for true_label,cluster_label in zip(row_ind,col_ind):
  aligned_labels[y_kmeans==cluster_label]=true_label
aligned_cm = confusion_matrix(y,aligned_labels)
print("\nAligned Confusion Matrix:\n",aligned_cm)
print("\nAccuracy:",accuracy_score(y,aligned_labels))


Aligned Confusion Matrix:
 [[50  0  0]
 [ 0 47  3]
 [ 0 14 36]]

Accuracy: 0.8866666666666667
